config/routes.rb
Rails.application.routes.draw do
  root to: "jewels#index"
  devise_for :users
  resources :users, only: [:index, :show]
  resources :jewels do
    resources :reviews, except: [:index, :show]
  end

  match('/reviews/:id/upvotes', {:via => :post, :to => 'upvotes#create', as: :review_upvotes})
  match('/reviews/:id/downvotes', {:via => :post, :to => 'downvotes#create', as: :review_downvotes})
end

app/models/downvote.rb
class Downvote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :review_id
end

app/models/jewel.rb
class Jewel < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  validates :url, presence: true, uniqueness: true

  has_many :reviews

  default_scope { order(:name) }
end

app/models/review.rb
class Review < ActiveRecord::Base
  validates :title, presence: true
  validates :text, presence: true

  belongs_to :user
  belongs_to :jewel

  has_many :upvotes
  has_many :downvotes

  default_scope { order('created_at DESC') }
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :review
  belongs_to :user

  validates_uniqueness_of :user_id, scope: :review_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:account_update) << :email
  end
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @review = Review.find(params[:id])
    @downvote = @review.downvotes.new(user_id: current_user.id)
    if @downvote.save
      respond_to do |format|
        format.html { redirect_to jewel_path(@review.jewel) }
        format.js
      end
    end
  end
end

app/controllers/jewels_controller.rb
class JewelsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @jewels = Jewel.all
  end

  def show
    @jewel = Jewel.find(params[:id])
    @review = @jewel.reviews.new
  end

  def new
    @jewel = Jewel.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @jewel = Jewel.new(jewel_params)
    if @jewel.save
      respond_to do |format|
        format.html { redirect_to root_path}
        format.js
      end
    else
      render 'new'
    end
  end

  def edit
    @jewel = Jewel.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @jewel = Jewel.find(params[:id])
    if @jewel.update(jewel_params)
      respond_to do |format|
        format.html { redirect_to jewel_path(@jewel) }
        format.js
      end
    end
  end

  def destroy
    @jewel = Jewel.find(params[:id])
    @jewel.reviews.destroy_all
    @jewel.destroy
    redirect_to jewels_path
  end

private
  def jewel_params
    params.require(:jewel).permit(:name, :url)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :authenticate_user!

  def new
    @jewel = Jewel.find(params[:jewel_id])
    @review = @jewel.reviews.new
    respond_to do |format|
      format.js
    end
  end

  def create
    @jewel = Jewel.find(params[:jewel_id])
    @review = @jewel.reviews.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      respond_to do |format|
        format.html { redirect_to jewel_path(@jewel)}
        format.js
      end
    else
      render 'new'
    end
  end

  def edit
    @jewel = Jewel.find(params[:jewel_id])
    @review = Review.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @jewel = Jewel.find(params[:jewel_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      respond_to do |format|
        format.html { redirect_to jewel_path(@jewel) }
        format.js
      end
    end
  end

  def destroy
    @jewel = Jewel.find(params[:jewel_id])
    @review = Review.find(params[:id])
    @review.destroy
    respond_to do |format|
      format.html { redirect_to jewel_path(@jewel) }
      format.js
    end
  end

private
  def review_params
    params.require(:review).permit(:title, :text)
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @review = Review.find(params[:id])
    @upvote = @review.upvotes.create(user_id: current_user.id)
    # if @upvote.save
      # respond_to do |format|
      #   format.js
      # end
    # end
    redirect_to jewel_path(@review.jewel)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/downvotes/create.js.erb
$('#review-downvotes-<%= @review.id %>').text(<%= @review.downvotes.count %>)

app/views/jewels/_form.html.erb
<%= form_for @jewel, remote: true do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>
  <%= f.submit(class: "btn btn-success") %>
<% end %>

app/views/jewels/_jewel.html.erb
<li><%= link_to jewel.name, jewel_path(jewel) %> <span class='badge'><%= jewel.reviews.count %> reviews</span></li>

app/views/jewels/create.js.erb
$('#new_jewel').hide();
$('#new-jewel-link').show();
$('#all-jewels').append('<%= j render(@jewel) %>');

app/views/jewels/edit.js.erb
$('#edit-jewel-link').hide()
$('#edit-form-goes-here').after('<%= j render("form") %>')

app/views/jewels/index.html.erb
<div class="jumbotron">
  <h1>Gem Reviews</h1>
  <p>Trying out a new gem? Share your experiences here or read about how it's worked for others.</p>
</div>
<ul id="all-jewels">
  <%= render @jewels %>
</ul>
<%= link_to "Add a gem", new_jewel_path, id: "new-jewel-link", class: "btn btn-primary", remote: true %>

app/views/jewels/new.html.erb
<h3>Create a new gem</h3>

<%= render 'form' %>

app/views/jewels/new.js.erb
$('#new-jewel-link').hide().after('<%= j render("form") %>')

app/views/jewels/show.html.erb
<div class="page-header">
  <h1><span id="jewel-name"><%= @jewel.name %></span> <small><span id= "jewel-url"><%= @jewel.url %></span>
  <% if user_signed_in? %>
     <%= link_to "Edit", edit_jewel_path(@jewel), id: "edit-jewel-link", class: "btn btn-default", remote: true %> <%= link_to "Delete", jewel_path(@jewel), id: "delete-jewel", class: "btn btn-danger", method:"delete" %>
  <% end %>
  </small></h1>
</div>
<span id="edit-form-goes-here"></span>
<div id="all-reviews">
  <span id="edit-review-form-goes-here"></span>
  <%= render @jewel.reviews %>
</div>
<%= link_to "Add a review", new_jewel_review_path(@jewel, @review), id: "new-review-link", class: "btn btn-primary", remote: true %>

app/views/jewels/update.js.erb
$('#edit-jewel-link').show();
$('#jewel-name').text("<%= @jewel.name %>");
$('#jewel-url').text("<%= @jewel.url %>");
$('#edit_jewel_<%= @jewel.id %>').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gemreviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to "Gem Reviews", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li></li>
      </ul>
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, method: "delete", class: "btn-sm btn-primary pull-right" %>
        <%= link_to 'Account', edit_user_registration_path, class: "btn-sm btn-warning pull-right" %>
        <%= link_to "#{current_user.name}'s Profile", user_path(current_user), class: "btn-sm btn-info pull-right" %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn-sm btn-default pull-right" %>
        <%= link_to "Login", new_user_session_path, class: "btn-sm btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</nav>
<%= flash[:notice] %>
<%= flash[:alert] %>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for [@jewel, @review], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :text %>
    <%= f.text_field :text %>
  </div>
  <%= f.submit(class: "btn btn-success") %>
<% end %>

app/views/reviews/_review.html.erb
<% if review.id != nil %>
  <div class="panel panel-default" id="review_<%= review.id %>">
    <div class="panel-heading">
      <h3 class="panel-title">
        <span id="review-title-<%= review.id %>"><%= review.title %></span>
        <%= link_to "<span class='glyphicon glyphicon-thumbs-up'>".html_safe, review_upvotes_path(review), method: "post", remote: true %></span>
        <span id="review-upvotes-<%= review.id %>"><%= review.upvotes.count %></span>
        <%= link_to "<span class='glyphicon glyphicon-thumbs-down'>".html_safe, review_downvotes_path(review), method: "post", remote: true %></span>
        <span id="review-downvotes-<%= review.id %>"><%= review.downvotes.count %></span>
        <% if current_user == review.user %>
          <%= link_to "Delete", jewel_review_path(review.jewel,review), id: "delete-review-link-#{review.id}", class: "pull-right", method: "delete", remote: true %>
          <%= link_to "Edit", edit_jewel_review_path(review.jewel,review), id: "edit-review-link-#{review.id}", class: "edit-review-links pull-right", remote: true %>
        <% end %>
        <%= link_to review.user.name, user_path(review.user), class: "pull-right" %>
      </h3>
    </div>
    <div class="panel-body">
      <p><em>created on <%= review.created_at %></em></p>
      <p><span id="review-text-<%= review.id %>"><%= review.text %></span></p>
    </div>
  </div>
<% end %>

app/views/reviews/create.js.erb
$('#new_review').hide();
$('#new-review-link').show();
$('#all-reviews').prepend('<%= j render(@review) %>');

app/views/reviews/destroy.js.erb
$('#review_<%= @review.id %>').remove()

app/views/reviews/edit.js.erb
$('.edit-review-links').hide()
$('#edit-review-form-goes-here').after('<%= j render("form") %>')

app/views/reviews/new.html.erb
<h3>Create a new review</h3>

<%= render 'form' %>

app/views/reviews/new.js.erb
$('#new-review-link').hide().after('<%= j render("form") %>')

app/views/reviews/update.js.erb
$('.edit-review-links').show();
$('#review-title-<%= @review.id %>').text("<%= @review.title %>");
$('#review-text-<%= @review.id %>').text("<%= @review.text %>");
$('#edit_review_<%= @review.id %>').hide();

app/views/upvotes/create.js.erb
$('#review-upvotes-<%= @review.id %>').text(<%= @review.upvotes.count %>)

app/views/users/index.html.erb
<h1>all our users</h1>
<ul>
  <% @users.each do |user| %>
    <li><%= user.name %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= @user.name %> <small><%= @user.email %> <span class='badge'><%= @user.reviews.count %> reviews</span></small></h1>
</div>

<h3>Gems reviewed:</h3>
<ul>
  <% @user.reviews.each do |review| %>
    <li><%= link_to review.jewel.name, jewel_path(review.jewel) %></li>
  <% end %>
</ul>